= Fulcro RAD NativeBase UI Rendering Plugin

A plugin to render forms and reports in React Native using components from the NativeBase UI library.

WARNING: This library is alpha.

== Usage

image:https://img.shields.io/clojars/v/com.fulcrologic/fulcro-rad-nativebase-ui.svg[link=https://clojars.org/com.fulcrologic/fulcro-rad-nativebase-ui]

To use this library simply install the controls on your RAD application:

[source]
-----
(ns com.example.main
  (:require
    [com.fulcrologic.rad.nativebase.ui-controls :as nb]
    [com.fulcrologic.rad.application :as rad-app]))

(defonce app (-> (rad-app/fulcro-rad-app)
                 (rad-app/install-ui-controls! nb/all-controls)))
-----

TODO: You will also need to change the state machine that is used by default for the forms. This needs a RAD patch.

== LICENSE

The MIT License (MIT)
Copyright (c), Fulcrologic, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

